# Default configuration for the GPG Spring Boot service
server.port=${SERVER_PORT:8080}
# Uncomment to specify default keyrings
# gpg.public-keyring=/data/pubring.gpg
# gpg.secret-keyring=/data/secring.gpg
# gpg.trust-model=always
