#!/usr/bin/env bash
set -euo pipefail

# This helper prepares a deterministic GPG environment for the Spring Boot service.
# It imports the configured keys and, when explicitly requested, performs a sample
# encryption so the service has something to decrypt.

: "${GPG_HOME:=${HOME}/.gnupg}"
: "${GPG_PUBLIC_KEY_PATH:=resources/junit/pubkey.asc}"
: "${GPG_SECRET_KEY_PATH:=resources/junit/seckey.asc}"
: "${GPG_ENCRYPT_SOURCE_PATH:=}"
: "${GPG_ENCRYPT_RECIPIENT:=}" # Fingerprint or UID for encryption
: "${GPG_ENCRYPT_OUTPUT_PATH:=}"
: "${GPG_SECRET_PASSPHRASE:=}"

export GNUPGHOME="$GPG_HOME"
mkdir -p "$GNUPGHOME"
chmod 700 "$GNUPGHOME"

echo "[initialize-gpg] Importing public key from $GPG_PUBLIC_KEY_PATH"
gpg --batch --yes --import "$GPG_PUBLIC_KEY_PATH"

echo "[initialize-gpg] Importing secret key from $GPG_SECRET_KEY_PATH"
gpg --batch --yes --import "$GPG_SECRET_KEY_PATH"

gpg --batch --yes --list-keys

echo "[initialize-gpg] Key material imported."

if [[ -n "$GPG_ENCRYPT_SOURCE_PATH" && -n "$GPG_ENCRYPT_RECIPIENT" && -n "$GPG_ENCRYPT_OUTPUT_PATH" ]]; then
  echo "[initialize-gpg] Encrypting $GPG_ENCRYPT_SOURCE_PATH for $GPG_ENCRYPT_RECIPIENT"
  gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_SECRET_PASSPHRASE" \
    --output "$GPG_ENCRYPT_OUTPUT_PATH" --encrypt --recipient "$GPG_ENCRYPT_RECIPIENT" "$GPG_ENCRYPT_SOURCE_PATH"
  echo "[initialize-gpg] Ciphertext written to $GPG_ENCRYPT_OUTPUT_PATH"
else
  cat <<INFO
[initialize-gpg] Encryption skipped.
Set GPG_ENCRYPT_SOURCE_PATH, GPG_ENCRYPT_RECIPIENT and GPG_ENCRYPT_OUTPUT_PATH to perform an encryption run.
No binary artifacts are generated by default.
INFO
fi
